"""Style inspection and modification."""

from docx_plus.styles.inspect import (
    FormattingSource,
    MissingPartError,
    ParagraphSpacing,
    ResolvedFormatting,
    StyleCascadeError,
    TableContext,
    resolve_effective_formatting,
    resolve_paragraph_spacing,
)
from docx_plus.styles.modify import (
    InvalidColorError,
    StyleExistsError,
    StyleInfo,
    StyleInUseError,
    StyleNotFoundError,
    StyleProxy,
    UnknownStylePropertyError,
    apply_style,
    create_style,
    delete_style,
    ensure_style,
    find_matching_style,
    find_unused_styles,
    list_styles,
    modify_style,
    remap_styles,
)
from docx_plus.styles.sweep import (
    ResolvedParagraph,
    ResolvedRun,
    iter_resolved_paragraphs,
)

__all__ = [
    "FormattingSource",
    "InvalidColorError",
    "MissingPartError",
    "ParagraphSpacing",
    "ResolvedFormatting",
    "ResolvedParagraph",
    "ResolvedRun",
    "StyleCascadeError",
    "StyleExistsError",
    "StyleInUseError",
    "StyleInfo",
    "StyleNotFoundError",
    "StyleProxy",
    "TableContext",
    "UnknownStylePropertyError",
    "apply_style",
    "create_style",
    "delete_style",
    "ensure_style",
    "find_matching_style",
    "find_unused_styles",
    "iter_resolved_paragraphs",
    "list_styles",
    "modify_style",
    "remap_styles",
    "resolve_effective_formatting",
    "resolve_paragraph_spacing",
]
